### ISSUE TITLE
Unaccepted result when parsing accept language header

### ISSUE THREAD

**Issue by vkononov** [cyril/accept_language.rb#4]
Both `AcceptLanguage.parse('en-us').match(*%i[de en])` and `AcceptLanguage.parse('en-ca').match(*%i[de en])` return `nil` while I would except them both to return `:en`.

Is this a bug, or am I missing something?

**Comment by cyril** [comment]
This is the expected behavior. The client requests content in United States English (or in Canada English), but the server only supports standard English and standard German. This is not exactly what is required by the client, so there is no match.

To get the desired behavior, I would suggest adapting the preferences as follows:

> en-us, en;q=0.1

Thus, standard English can be accepted as a last resort:

```ruby
AcceptLanguage.parse("en-us, en;q=0.1").match(:de, :en) # => :en
```

**Comment by vkononov** [comment]
Thanks for your answer, @cyril.

Just to clarify, if I follow the following example from your tool:

```
string = request.headers.fetch("HTTP_ACCEPT_LANGUAGE")
locale = AcceptLanguage.parse(string).match(*I18n.available_locales)
```

and my browser language is set to German, while the default language is set to English, I would see content in English even when German is available. It's generally infeasible to provide translations for `de-at`, `de-ch`, `de-li`, etc, so all of these users would see English even though `de` is available.

Is this really the right approach? How would you recommend handling the proper German fallback when using `request.headers.fetch("HTTP_ACCEPT_LANGUAGE")`?

**Comment by cyril** [comment]
You're welcome.

> Just to clarify, if I follow the following example from your tool:

```ruby
string = request.headers.fetch("HTTP_ACCEPT_LANGUAGE")
locale = AcceptLanguage.parse(string).match(*I18n.available_locales)
```

> and my browser language is set to German

In this case, your browser should have this HTTP request header: `Accept-Language: de`

> while the default language is set to English,

Okay. So let's imagine that the server only supports English (which is therefore necessarily the default language).

> I would see content in English even when German is available.

Yes, in this case the server should return English content to the browser. But German is not available in this scenario.

> It's generally infeasible to provide translations for `de-at`, `de-ch`, `de-li`, etc, so all of these users would see English even though `de` is available.

Yes, dialects are probably less often supported than standard languages by servers. I mean, official national languages are more often available.

The strategy I would recommend is to list the languages you want to get first, even if they are rarely supported, it doesn't matter. In your case, it's some German dialects if I'm not mistaken.

Then you can define a popular language as a fallback, in case your preferred languages are not supported by the server.

For example, it is more common for web servers to support the German language rather than the Swiss German dialect.

And sometimes English is supported by the server, but German is not. Or the other way around.

In any case, if you wish to accept the English language as a backup in the event that the German language is completely unavailable, it would be possible to add it to the bottom of the list (low priority).

Here is an example with several languages accepted by the browser, requested by the client to the server:

1. Ideally, I would like to get a web page in German (Austria).
2. If this is not possible, then I will settle for a web page in German (Switzerland).
3. If this is not possible, then I will settle for a web page in German (Liechtenstein).
4. If this is not possible, then I will settle for a web page in German (Germany).
5. If this is not possible, then I will settle for a web page in German (standard).
6. If this is not possible, then I will settle for a web page in English (USA).
7. If this is not possible, then I will settle for a web page in English (standard).

The corresponding HTTP request header could be:

```http
Accept-Language: de-AT,de-CH;q=0.9,de-LI;q=0.8,de-DE;q=0.7,de;q=0.6,en-US;q=0.5,en;q=0.4
```

Now, let's assume that the querying server only knows English. Unfortunately, this case can often happen. The language selected by the server to return the web page would be English:

```ruby
string = "de-AT,de-CH;q=0.9,de-LI;q=0.8,de-DE;q=0.7,de;q=0.6,en-US;q=0.5,en;q=0.4"
AcceptLanguage.parse(string).match(:en) # => :en
```

If German is also supported by the server, things can get better:

```ruby
string = "de-AT,de-CH;q=0.9,de-LI;q=0.8,de-DE;q=0.7,de;q=0.6,en-US;q=0.5,en;q=0.4"
AcceptLanguage.parse(string).match(:en, :de) # => :de
```

And if a German dialect (e.g. Swiss German) is also supported, even better:

```ruby
string = "de-AT,de-CH;q=0.9,de-LI;q=0.8,de-DE;q=0.7,de;q=0.6,en-US;q=0.5,en;q=0.4"
AcceptLanguage.parse(string).match(:en, :de, :"de-CH") # => :"de-CH"
```

I hope that the behavior of this gem has no more secret for you.

**Comment by vkononov** [comment]
@cyril Thank you so much for such a detailed response. That cleans up a lot of things. Very informative!
