### ISSUE TITLE
Can't upgrade gem to 2.0.4 on Ruby 3.0.6. Required Ruby version got bumped from 2.7.6 to 3.1.4 by mistake?

### ISSUE THREAD

**Issue by philippeapril** [cyril/accept_language.rb#6]
The required ruby version in accept_language.gemspec got bumped from 2.7.6 to 3.1.4 in commit [9a651d7](https://github.com/cyril/accept_language.rb/commit/9a651d7a3c211bc34091af878195e0754062f8a4) where there are mainly documentation changes and it's making it incompatible with any ruby version earlier than that.

Was it a desired change or a mistake? I really doubt it's now the minimum required version.

Here's what I'm getting if I try to update from 2.0.3 to 2.0.4 on a Rails 7 app using Ruby 3.0.6.

```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions

Because accept_language >= 2.0.4 depends on Ruby >= 3.1.4
  and Gemfile depends on accept_language ~> 2.0.4,
  Ruby >= 3.1.4 is required.
So, because current Ruby version is = 3.0.6,
  version solving has failed.
```

**Comment by cyril** [comment]
Hi @philippeapril,

Thanks for reaching out about the Ruby version update in `accept_language.gemspec` to 3.1.4. This change was intentional due to Ruby 2.7 no longer being maintained by the core team, affecting long-term support and security.

If upgrading to Ruby 3.1.4 is not an option for you at the moment, you can continue using `Accept Language` gem version 2.0.3, which has identical code to the latest version but supports older Ruby versions.

I apologize for any inconvenience this may have caused.

Best,
Cyril
